### PR TITLE
Add internal macro to make tests of `nest` easier to write

### PR DESCRIPTION
**Pull request by davidpdrsn**
This might be considered a dirty hack but stick with me.

There have been talk about changing `nest` back to how it worked in 0.5, where it would "flatten" the routes into the outer router. That should fix the [performance regression](https://github.com/tokio-rs/axum/issues/1624) and the [`MatchedPath` issues](https://github.com/tokio-rs/axum/issues/1441) people have reported.

However the reason I change `nest` in 0.6 to just call `nest_service` was to more the subtle differences between the two methods. So if we're gonna back I wanna make sure we aren't introducing new differences.

One way to do that is for each test that uses `nest`, write the same test but use `nest_service`. That obviously kinda tedious to do manually but easy to do in a macro. So this PR adds such a macro.

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
Hm, how does this not cause compilation errors for cases where the inner Router has a non-unit state type?

**Comment by davidpdrsn** [comment]
It does so for such test we wouldn't be able to use it.

**Comment by jplatte** [comment]
Do we not have such tests yet? It seems to me like you just search&replace'd all the `tokio::test`s, why not be a little more selective?

**Review by jplatte — APPROVED** [review]
Other than that the macro is maybe overused a little, LGTM.

**Comment by davidpdrsn** [comment]
> Do we not have such tests yet? 

Apparently not 😅 I think those tests are doctests actually.

> It seems to me like you just search&replace'd all the tokio::tests, why not be a little more selective?

Yeah I did. Thought that was easier and shouldn't have any impact when used on functions that don't use `nest`.
