### ISSUE TITLE
v7.x Breaks AWS HTTP Lambda Example

### ISSUE THREAD

**Issue by DavidAChris** [tokio-rs/axum#2370]
- [x] I have looked for existing issues (including closed) about this

### Version
v7.x

### Crates
[dependencies]
axum = "0.7"
lambda_http = "0.8"
lambda_runtime = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
] }

### Description
In summary, the AWS Lambda example we could previously use Axum up to v6.x. After upgrading to v7.x, I get errors because of possibly an incompatibility. I was able to track it down to a removal of generics in the Router Struct. Please see below in breaking changes. Appologies if this is an intended change; however, I could not find information in the documentation in a different way to setup a Router so that it may be compatible with the AWS example, if its simply no longer possible to use in Lambda thats fine as well, I wanted to at least bring it to your attention. Thanks!

If you upgrade this example to v.7.x then this is no longer possible
https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/examples/http-axum

v7.x:
    axum::routing
    pub struct Router<S = ()> {
        path_router: PathRouter<S, false>,
        fallback_router: PathRouter<S, true>,
        default_fallback: bool,
        catch_all_fallback: Fallback<S, Infallible>,
    }

v6.x:
    axum::routing
    pub struct Router<S = (), **B = Body**> {
        path_router: PathRouter<S, B, false>,
        fallback_router: PathRouter<S, B, true>,
        default_fallback: bool,
        catch_all_fallback: Fallback<S, B, Infallible>,
    }

v7.x <error msg>:
    error[E0277]: the trait bound `Router<_>: Service<lambda_http::http::Request<lambda_http::Body>>` is not satisfied
    --> src/main.rs:51:9
        |
    51  |     run(app).await
        |     --- ^^^ the trait `Service<lambda_http::http::Request<lambda_http::Body>>` is not implemented for `Router<_>`
        |     |
        |     required by a bound introduced by this call
        |
        = help: the following other types implement trait `Service<Request>`:
                <Router as Service<axum::http::Request<B>>>
                <Router as Service<IncomingStream<'_>>>
    note: required by a bound in `lambda_http::run`
    --> /Users/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lambda_http-0.8.3/src/lib.rs:191:8
        |
    189 | pub async fn run<'a, R, S, E>(handler: S) -> Result<(), Error>
        |              --- required by a bound in this function
    190 | where
    191 |     S: Service<Request, Response = R, Error = E>,
        |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `run`

    For more information about this error, try `rustc --explain E0277`.
